vich_uploader:
    db_driver: orm

    mappings:
        book_images:
            uri_prefix: '%book_images%'
            upload_destination: '%kernel.project_dir%/public%book_images%'
            namer : Vich\UploaderBundle\Naming\UniqidNamer
            #Pour éviter de supprimmer lors d'un update ou d'un déplacement
            #delete_on_update: false
            #delete_on_remove: false

    #mappings:
    #    book_image:
    #        uri_prefix: /images/books
    #        upload_destination: '%kernel.project_dir%/public/images/books'
    #        namer : Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
